""" Color dictionaries """

colors_per_STN = {
    "017_Right": "orchid",
    "017_Left": "darkviolet",
    "019_Right": "darkcyan",
    "019_Left": "turquoise",
    "021_Right": "peachpuff",
    "021_Left": "tan",
    "024_Right": "dimgray",
    "024_Left": "lightgray",
    "025_Right": "darkred",
    "025_Left": "lightcoral",
    "026_Right": "seagreen",
    "026_Left": "mediumspringgreen",
    "028_Right": "yellow",
    "028_Left": "gold",
    "029_Right": "dodgerblue",
    "029_Left": "lightskyblue",
    "030_Right": "navy",
    "030_Left": "blue",
    "031_Right": "pink",
    "031_Left": "plum",
    "032_Right": "magenta",
    "032_Left": "purple",
    "033_Right": "saddlebrown",
    "033_Left": "sandybrown",
    "038_Right": "greenyellow",
    "038_Left": "yellowgreen"
}